Task4Start/Controllers/BusinessUnitsController.cs
using System.Net.Http;
using System.Web.Mvc;
using System.Threading.Tasks;
using Task4Start.Models;
using SkillsCoDbfModel;
using Task4Start.Repository;
using Task4Start.SkillService;
using System;

namespace Task4Start.Controllers
{
    public class BusinessUnitsController : Controller
    {
        private IDataRepository dataRepository;
        private ISkillsRepository skillsRepository;
        private IAdminRepository adminRepository;

        /// <summary>
        /// Default Constructor.
        /// Instantiates objects for the required Repository/DAL interfaces.
        /// </summary>
        public BusinessUnitsController()
        {
            this.dataRepository = new DataRepository(new StaffSkillsModel());
            this.skillsRepository = new SkillsRepository(new SkillServiceClient());
            this.adminRepository = new AdminRepository(new HttpClient());
        }



        /// <summary>
        /// Controller action to display a list/index of available business units.
        /// </summary>
        /// <returns>A view model to display.</returns>
        // GET: BusinessUnit
        public async Task<ActionResult> Index()
        {
            try
            {
                HttpResponseMessage response = await adminRepository.RetryGetBu();

                var viewModel = await BusinessUnitVM.buildList(response);

                return View(viewModel);
            }
            catch (Exception e)
            {
                // Incase of an exception then user is directed to the last page that can be correctly displayed.
                return RedirectToAction("Index", "Home");
            }
        }



        /// <summary>
        /// Controller action to display a list of staff associated with the a business unit.
        /// </summary>
        /// <param name="id">The selected business unit.</param>
        /// <returns>A view model to display.</returns>
        // GET: BusinessUnit/BuStaff/ABC
        public async Task<ActionResult> BuStaff(string id)
        {
            try
            {
                HttpResponseMessage response = await adminRepository.RetryGetBuStaff(id);

                var viewModel = await StaffVM.buildList(response, id);

                return View(viewModel);
            }
            catch (Exception e)
            {
                // Incase of an exception then user is directed to the last page that can be correctly displayed.
                return RedirectToAction("Index");
            }
        }



        /// <summary>
        /// Controller action to display a list of skills associated with a business unit.
        /// </summary>
        /// <param name="id">The selected business unit.</param>
        /// <returns>A view model to display.</returns>
        // GET: BusinessUnit/BuSkills/ABC
        public async Task<ActionResult> BuSkills(string id)
        {
            try
            {
                HttpResponseMessage response = await adminRepository.RetryGetBuStaff(id);
                
                var skills = await skillsRepository.RetryGetSkills();

                var allStSkills = await dataRepository.GetStaffSkills();

                var viewModel = await SkillVM.buildList(skills, response, allStSkills, id);

                return View(viewModel);
            }
            catch (Exception e)
            {
                // Incase of an exception then user is directed to the last page that can be correctly displayed.
                return RedirectToAction("Index");
            }
        }

    }
}

Task4Start/Controllers/StaffsController.cs
using SkillsCoDbfModel;
using System;
using System.Threading.Tasks;
using System.Web.Mvc;
using Task4Start.Models;
using Task4Start.Repository;
using Task4Start.SkillService;

namespace Task4Start.Controllers
{
    public class StaffsController : Controller
    {
        private IDataRepository dataRepository;
        private ISkillsRepository skillsRepository;

        /// <summary>
        /// Default Constructor.
        /// Instantiates objects for the required Repository/DAL interfaces.
        /// </summary>
        public StaffsController()
        {
            this.dataRepository = new DataRepository(new StaffSkillsModel());
            this.skillsRepository = new SkillsRepository(new SkillServiceClient());
        }



        /// <summary>
        /// Controller action to display a list of a staff members skills.
        /// </summary>
        /// <param name="id">The member of staff.</param>
        /// <returns>A view model to display.</returns>
        // GET: Staff/StaffSkills/ABC
        public async Task<ActionResult> StaffSkills(string id)
        {
            try
            {
                var stSkills = await dataRepository.GetAStaffsSkills(id);

                var viewModel = SkillVM.buildList(stSkills, id);
                
                return View(viewModel);
            }
            catch (Exception e)
            {
                // Incase of an exception then user is directed to the last page that can be correctly displayed.
                return RedirectToAction("Index", "BusinessUnits");
            }
        }



        /// <summary>
        /// Controller action to select an available skill to add to a member of staff.
        /// </summary>
        /// <param name="id">The member of staff.</param>
        /// <returns>A view model to display.</returns>
        // GET: Staff/AddSkill/ABC
        public async Task<ActionResult> AddSkill(string id)
        {
            try
            {
                var skills = await skillsRepository.RetryGetSkills();

                var stSkills = await dataRepository.GetAStaffsSkills(id);

                SkillVM viewModel = new SkillVM();

                viewModel.buildSkList(skills, stSkills, id);
                
                return View(viewModel);
            }
            catch (Exception e)
            {
                // Incase of an exception then user is directed to the last page that can be correctly displayed.
                return RedirectToAction("Index", "BusinessUnits");
            }
        }



        /// <summary>
        /// Controller action to add a skill to a member of staff.
        /// </summary>
        /// <param name="skillVM">The member of staff selected.</param>
        /// <returns>A redirect to the "StaffSkills" action.</returns>
        // POST: Staff/AddSkill/ABC
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddSkill([Bind(Include = "staffCode, selectedSkCode")] SkillVM skillVM)
        {
            try
            {
                var model = SkillVM.buildModel(skillVM);

                dataRepository.SaveModel(model);

                return RedirectToAction("StaffSkills", new { id = skillVM.staffCode });
            }
            catch (Exception e)
            {
                // Incase of an exception then user is directed to the last page that can be correctly displayed.
                return RedirectToAction("StaffSkills", new { id = skillVM.staffCode });
            }
        }

    }
}

Task4Start/Views/BusinessUnits/BuSkills.cshtml
@model Task4Start.Models.SkillVM

@{
    ViewBag.Title = "BuSkills";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.DisplayFor(model => model.businessUnitCode) Skills</h2>
<br>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.skillCode)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model.skUnits)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.skillCode)
        </td>
    </tr>
}

</table>

<div>
    @Html.ActionLink("Back", "Index")
</div>

Task4Start/Views/BusinessUnits/BuStaff.cshtml
@model Task4Start.Models.StaffVM

@{
    ViewBag.Title = "BuStaff";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>@Html.DisplayFor(model => model.businessUnitCode) Staff</h2>
<br>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.staffCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.fullName)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.stUnits)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.staffCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fullName)
            </td>
            <td>
                @Html.ActionLink("View Skills", "StaffSkills", "Staffs", new { id = item.staffCode }, null)
            </td>
        </tr>
    }

</table>

<div>
    @Html.ActionLink("Back", "Index")
</div>

Task4Start/Views/BusinessUnits/Index.cshtml
@model IEnumerable<Task4Start.Models.BusinessUnitVM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Business Units</h2>
<br>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.businessUnitCode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.businessUnitCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.ActionLink("Staff", "BuStaff", new { id = item.businessUnitCode }) |
            @Html.ActionLink("Skills Resources", "BuSkills", new { id = item.businessUnitCode })
        </td>
    </tr>
}

</table>